{"uuid": "92e3fea5-5564-4b00-8a0b-78a463bffc60", "children": ["316ca60c-9791-42ff-bd22-3082c73a1c86", "79dc59f7-c6e6-4e4a-aba9-18c7def24278", "cfb22eeb-ffda-4840-b545-ed485d5a900c", "391f3261-d215-49a8-8aba-f001dfb45084", "e2512d03-b5a9-4f1c-b597-6a127a18fbfa", "2e363da4-328a-474e-bb06-cb8fe2be1b63", "2ebff856-5a6d-4766-8eb6-4f93cd85f961", "9ff16d9b-586d-4815-8286-ea20295f7f7b", "d241914c-e2cb-4e10-bcce-c3c441cfd6d3", "3f20ec6b-0af8-4103-9d74-aa36e79a45a6", "a7e73e2d-48b8-46d3-8275-390ff58aac36", "c5a8f6ff-969d-4e21-9607-ba5f68c2603a", "66ae10ed-2096-4cc7-ba05-7b0aaddcfb0f"], "befores": [{"name": "fix_module", "status": "broken", "statusDetails": {"message": "json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 2)\n", "trace": "  File \"C:\\Users\\luban\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\luban\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\luban\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"F:\\BaiduNetdiskDownload\\api_base\\conftest.py\", line 59, in fix_module\n    res_status, login_res = fix_login_res.status_code, fix_login_res.json()\n  File \"C:\\Users\\luban\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages\\requests\\models.py\", line 900, in json\n    return complexjson.loads(self.text, **kwargs)\n  File \"C:\\Users\\luban\\AppData\\Local\\Programs\\Python\\Python37\\lib\\json\\__init__.py\", line 348, in loads\n    return _default_decoder.decode(s)\n  File \"C:\\Users\\luban\\AppData\\Local\\Programs\\Python\\Python37\\lib\\json\\decoder.py\", line 337, in decode\n    obj, end = self.raw_decode(s, idx=_w(s, 0).end())\n  File \"C:\\Users\\luban\\AppData\\Local\\Programs\\Python\\Python37\\lib\\json\\decoder.py\", line 355, in raw_decode\n    raise JSONDecodeError(\"Expecting value\", s, err.value) from None\n"}, "steps": [{"name": "登录", "status": "passed", "parameters": [{"name": "mobile", "value": "18012345678"}, {"name": "password", "value": "123456"}, {"name": "env_url", "value": "'http://www.baseb.com'"}], "start": 1618237475334, "stop": 1618237478947}], "start": 1618237475334, "stop": 1618237478948}], "start": 1618237475334, "stop": 1618237479679}